import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {journey,samples,annualSaved} from '../src/models.mjs';
import {root,build,renderMarkdown,validatePost} from '../scripts/build.mjs';
test('journey preserves arrival temperature while cumulative exposure changes',()=>{for(const h of [0,.5,2,6]){const r=journey(h);assert.equal(r.points.at(-1)[1],4);assert.equal(r.exposure,h*12);}assert.throws(()=>journey(-1));});
test('sampling reveals aliasing and catches the peak at the expected interval',()=>{assert.equal(samples(30).peak,4);assert.equal(samples(60).peak,4);assert.equal(samples(10).peak,8);assert.equal(samples(5).peak,12);assert.equal(samples(15).peak,12);});
test('avoided loss uses throughput share, including zero and upper bounds',()=>{assert.equal(annualSaved(0),0);assert.equal(annualSaved(2),10400);assert.equal(annualSaved(10),52000);assert.throws(()=>annualSaved(NaN));});
test('Markdown keeps useful formatting and removes active content',()=>{const html=renderMarkdown('## Heading\n\n**Bold**\n\n<script>alert(1)</script><img src="x" onerror="alert(1)"><a href="javascript:alert(1)">x</a>');assert.match(html,/<h2>Heading<\/h2>/);assert.match(html,/<strong>Bold<\/strong>/);assert.doesNotMatch(html,/<script|onerror|javascript:/i);});
test('post validation rejects path traversal and unsafe cover links',()=>{const p={slug:'valid',title:'Title',summary:'Summary',date:'2026-09-06',status:'draft',body:'Text'};validatePost(p);assert.throws(()=>validatePost({...p,slug:'../secret'}));assert.throws(()=>validatePost({...p,cover:'javascript:alert(1)'}));});
test('export hides drafts, removes unpublished pages and gates academic sections',()=>{
 const base=path.join(root,'.test-fixture');fs.mkdirSync(path.join(base,'content/posts'),{recursive:true});fs.mkdirSync(path.join(base,'src'),{recursive:true});fs.copyFileSync(path.join(root,'src/home.html'),path.join(base,'src/home.html'));
 const site=JSON.parse(fs.readFileSync(path.join(root,'content/site.json'))),academic={publications:[{title:'Future paper',date:'2027',url:'https://example.org'}],talks:[],teaching:[],activities:[],cv:[]};
 site.notesEnabled=true;
 const write=(name,obj)=>fs.writeFileSync(path.join(base,'content',name),JSON.stringify(obj));write('site.json',site);write('academic.json',academic);
 const p={title:'Visible note',summary:'Summary',date:'2026-09-06',status:'published',category:'Test'};write('posts/visible.json',p);fs.writeFileSync(path.join(base,'content/posts/visible.md'),'Hello');write('posts/secret.json',{...p,title:'Secret draft',status:'draft'});fs.writeFileSync(path.join(base,'content/posts/secret.md'),'Never export this');
 build(base);let home=fs.readFileSync(path.join(base,'dist/index.html'),'utf8');assert.match(home,/Visible note/);assert.equal(fs.readFileSync(path.join(base,'index.html'),'utf8'),home);assert.ok(fs.existsSync(path.join(base,'assets/style.css')));assert.doesNotMatch(home,/Secret draft|Future paper|\{\{/);assert.equal(fs.existsSync(path.join(base,'dist/notes/secret/index.html')),false);assert.equal(fs.existsSync(path.join(base,'dist/studio')),false);
 site.notesEnabled=false;write('site.json',site);build(base);home=fs.readFileSync(path.join(base,'dist/index.html'),'utf8');assert.doesNotMatch(home,/id="notes"|href="#notes"|Visible note/);assert.equal(fs.existsSync(path.join(base,'dist/notes/visible/index.html')),false);assert.equal(fs.existsSync(path.join(base,'notes/visible/index.html')),false);site.notesEnabled=true;write('site.json',site);build(base);assert.equal(fs.existsSync(path.join(base,'dist/notes/visible/index.html')),true);
 p.status='draft';write('posts/visible.json',p);site.academic.publications=true;site.academic.talks=true;write('site.json',site);build(base);home=fs.readFileSync(path.join(base,'dist/index.html'),'utf8');assert.match(home,/Future paper/);assert.doesNotMatch(home,/id="talks"/);assert.equal(fs.existsSync(path.join(base,'dist/notes/visible/index.html')),false);
});
