import {seoHead,sitemap,robots} from './seo.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {marked} from 'marked';
import sanitizeHtml from 'sanitize-html';
export const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const out=path.join(root,'dist');
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(value){return typeof value==='string' && (/^https?:\/\//i.test(value)||/^\/(?!\/)/.test(value)) ? value : '';}
export function renderMarkdown(md){return sanitizeHtml(marked.parse(md),{allowedTags:[...sanitizeHtml.defaults.allowedTags,'img','figure','figcaption'],allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,img:['src','alt','title','width','height'],a:['href','title']},allowedSchemes:['http','https','mailto'],allowProtocolRelative:false});}
export function readPost(slug,base=root){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw Error('Use a lowercase, hyphenated slug');const meta=JSON.parse(fs.readFileSync(path.join(base,'content/posts',slug+'.json'),'utf8'));return {...meta,slug,body:fs.readFileSync(path.join(base,'content/posts',slug+'.md'),'utf8')};}
export function listPosts(base=root){return fs.readdirSync(path.join(base,'content/posts')).filter(f=>f.endsWith('.json')).map(f=>readPost(f.slice(0,-5),base)).sort((a,b)=>b.date.localeCompare(a.date));}
export function validatePost(p){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug||''))throw Error('Use a lowercase, hyphenated slug');if(!p.title?.trim()||!p.summary?.trim())throw Error('A title and summary are required');if(!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||Number.isNaN(Date.parse(p.date)))throw Error('Enter a valid date');if(!['draft','published'].includes(p.status))throw Error('Invalid status');if(p.cover&&!safeUrl(p.cover))throw Error('Cover must be a relative /assets/ path or an https URL');if(typeof p.body!=='string')throw Error('Article body is required');}
function header(){return `<header class="site-header wrap"><a class="wordmark" href="/"><span class="seed">◒</span> Zhong Chen<span class="brand-dot">.</span></a><nav aria-label="Main navigation"><a href="/#experiments">Play & learn</a><a href="/#notes">Notes</a><a href="/#about">About</a></nav></header>`;}
export function postPage(post,site=JSON.parse(fs.readFileSync(path.join(root,'content/site.json'),'utf8')),preview=false){return `<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(post.title)} — Zhong Chen</title><meta name="description" content="${esc(post.summary)}">${seoHead(site,post,preview||post.status==='draft')}<link rel="icon" href="/assets/seed.svg"><link rel="stylesheet" href="/assets/style.css"></head><body><a class="skip" href="#main">Skip to content</a>${header()}<main class="article" id="main"><a href="/#notes">← Back to notes</a><p class="note-meta">${esc(post.category)} · ${esc(post.date)} · ${Math.max(1,Math.ceil(post.body.split(/\s+/).length/200))} min read${post.status==='draft'?' · DRAFT PREVIEW':''}</p><h1>${esc(post.title)}</h1><p class="lede">${esc(post.summary)}</p>${post.cover?`<img class="cover" src="${esc(safeUrl(post.cover))}" alt="${esc(post.coverAlt||'')}">`:''}<div class="prose">${renderMarkdown(post.body)}</div>${post.aiNote?`<p class="editorial-note">${esc(post.aiNote)}</p>`:''}<p><a href="mailto:zhong@zhongchen.ai">Have another perspective? Let’s exchange ideas ↗</a></p></main><footer class="wrap site-footer"><span>© ${new Date().getFullYear()} Zhong Chen</span><a href="/">Back to the workbench</a></footer></body></html>`;}
const labels={publications:'Publications',talks:'Talks',teaching:'Teaching',activities:'Activities',cv:'CV'};
export function build(base=root){const out=path.join(base,'dist');fs.mkdirSync(out,{recursive:true});const written=[];function write(name,text){const dest=path.join(out,name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,text);written.push(name);}function copyDir(from,to){if(!fs.existsSync(from))return;for(const e of fs.readdirSync(from,{withFileTypes:true})){if(e.isDirectory())copyDir(path.join(from,e.name),path.join(to,e.name));else write(path.join(to,e.name),fs.readFileSync(path.join(from,e.name)));}}
 const site=JSON.parse(fs.readFileSync(path.join(base,'content/site.json'),'utf8')),academic=JSON.parse(fs.readFileSync(path.join(base,'content/academic.json'),'utf8'));const posts=listPosts(base);posts.forEach(validatePost);const notesEnabled=site.notesEnabled!==false;const published=notesEnabled?posts.filter(p=>p.status==='published'):[];
 copyDir(path.join(root,'assets'),'assets');for(const name of ['style.css','app.js','models.mjs'])write('assets/'+name,fs.readFileSync(path.join(root,'src',name)));
 // Publish only the two explicitly selected demonstrations; keep all other draft material private.
 for(const name of ['mvp','flow']){const source=path.join(root,'draft',name+'.html');if(fs.existsSync(source))write(`draft/${name}/index.html`,fs.readFileSync(source));}
 const cards=published.length?published.map(p=>`<a class="note-card" href="/notes/${p.slug}/">${p.cover?`<div class="note-art"><img src="${esc(safeUrl(p.cover))}" alt="${esc(p.coverAlt||'')}" loading="lazy"></div>`:''}<div class="note-meta">${esc(p.category)} · ${Math.max(1,Math.ceil(p.body.split(/\s+/).length/200))} min read</div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><span class="read-link">Read the note ↗</span></a>`).join(''):'<p>New notes are taking shape. In the meantime, explore the experiments above or <a href="mailto:'+esc(site.email)+'">send me a question</a>.</p>';
 let academicNav='',academicSections='';for(const [key,label] of Object.entries(labels)){const items=academic[key]||[];if(!site.academic[key]||!items.length)continue;academicNav+=`<a href="/#${key}">${label}</a>`;academicSections+=`<section class="wrap section" id="${key}"><h2>${label}</h2><ul class="academic-list">${items.map(item=>`<li><h3>${safeUrl(item.url)?`<a href="${esc(safeUrl(item.url))}">${esc(item.title)}</a>`:esc(item.title)}</h3><p>${esc(item.date||'')} ${esc(item.venue||'')}</p><p>${esc(item.description||'')}</p></li>`).join('')}</ul></section>`;}
 let socials='';for(const [key,label] of [['linkedin','LinkedIn'],['github','GitHub'],['scholar','Google Scholar'],['orcid','ORCID']])if(safeUrl(site[key]))socials+=`<a href="${esc(safeUrl(site[key]))}" target="_blank" rel="noopener">${label} ↗</a>`;
 let home=fs.readFileSync(path.join(base,'src/home.html'),'utf8');if(!notesEnabled)home=home.replace(/<!-- NOTES_START -->[\s\S]*?<!-- NOTES_END -->/,'');for(const [key,value] of Object.entries({SEO_TITLE:esc(site.title),SEO_DESCRIPTION:esc(site.description),SEO_HEAD:seoHead(site),EMAIL:esc(site.email),YEAR:new Date().getFullYear(),NOTES:cards,NOTES_NAV:notesEnabled?'<a href="#notes">Notes</a>':'',ABOUT_NUMBER:notesEnabled?'03':'02',SOCIAL_LINKS:socials,ACADEMIC_NAV:academicNav,ACADEMIC_SECTIONS:academicSections}))home=home.replaceAll('{{'+key+'}}',String(value));write('index.html',home);for(const post of published)write(`notes/${post.slug}/index.html`,postPage(post,site));
 write('sitemap.xml',sitemap(site,published));
 write('robots.txt',robots(site));
 write('404.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Page not found — Zhong Chen</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/assets/style.css"><main class="article"><h1>This page has moved.</h1><p><a href="/">Return to the workbench →</a></p></main></html>`);
 // Delete only previously generated files that became unpublished; leave unrelated files alone.
 const manifest=path.join(out,'.generated.json');if(fs.existsSync(manifest)){for(const old of JSON.parse(fs.readFileSync(manifest,'utf8'))){const dest=path.resolve(out,old);if(dest.startsWith(out+path.sep)&&!written.includes(old)&&fs.existsSync(dest)&&fs.statSync(dest).isFile())fs.unlinkSync(dest);}}
 fs.writeFileSync(manifest,JSON.stringify(written));
 // Also retain a ready-to-serve root for existing zero-build static deployments.
 // Only these generated files are touched; source assets and draft/ are never removed.
 const rootFiles=['index.html','404.html','robots.txt','sitemap.xml','assets/style.css','assets/app.js','assets/models.mjs',...published.map(p=>`notes/${p.slug}/index.html`)];
 const pageManifest=path.join(base,'.root-pages.json');
 const oldPages=fs.existsSync(pageManifest)?JSON.parse(fs.readFileSync(pageManifest,'utf8')):[];
 for(const old of oldPages){if(/^notes\/[a-z0-9]+(?:-[a-z0-9]+)*\/index\.html$/.test(old)&&!rootFiles.includes(old)){const file=path.join(base,old);if(fs.existsSync(file))fs.unlinkSync(file);}}
 for(const name of rootFiles){const dest=path.join(base,name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(out,name),dest);}
 fs.writeFileSync(pageManifest,JSON.stringify(rootFiles.filter(p=>p.startsWith('notes/')),null,2)+'\n');
 return {posts:published.length,drafts:posts.filter(p=>p.status==='draft').length,output:out};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(build());
